### ISSUE TITLE
[FEATURE]: Create RelativeTimeFormat Page

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#16]
## Summary

Like it is being done to the DateTimeFormat page let's do the same for RelativeTimeFormat page.

This issue will be labeled as `EPIC` so that PR`s for smaller parts can be open.
Ex: Layout, Links, Popovers, Form, Display (Result), Change Number, etc...

### Progress

- [x] Layout @jsilva234 (✅ merged)
- [x] Data @khuongTiet (✅ merged)
- [x] Form @khuongTiet (✅ merged)
- [ ] Links @luisFilipePT ✅ 

### Basic example

![image](https://user-images.githubusercontent.com/9373787/66743860-cb89d100-ee72-11e9-81f6-4b3d7cd8f491.png)

### Motivation

Continue adding pages 🎉

**Comment by jsilva234** [comment]
Hello,
I can start the layout.

Thanks

**Comment by luisFilipePT** [comment]
@jsilva234 go for it 🚀 
I will add that task assigned to you
