### ISSUE TITLE
[FEATURE]: Improve Overall Design (color pallete, disposition, docs, etc)

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#27]
## Summary

All the work done so far has come from developers (I think 🤔 ), it would be really nice if we could get some help improving our design and user experience

Right now only the Home Page is visible in the live version, the other pages the project needs to run locally (some screenshots attached)

I think it would be cool to create a `/docs/design/` folder and add some douments like:
- [ ] Design Guidelines
- [ ] Color Palete
- [ ] Screens design files
- [ ] Contributing to design
- [ ] Mobile versions (future)

Some useful links for the task:
- https://landing.ant.design/
- https://kitchen.alipay.com/
- https://ant.design/
- https://ant.design/docs/react/introduce

### Screenshots
Home Page
![image](https://user-images.githubusercontent.com/9373787/66777052-d6b71e00-eebf-11e9-9b78-584760f82e2f.png)

DateTimeFormat
![image](https://user-images.githubusercontent.com/9373787/66777095-f3535600-eebf-11e9-9d2d-57fd19d6e513.png)

### Motivation

I know this is a lot to ask, and the project is still changing fast but this would be really great 🎉 
I know the community is 💪 so this will 🚢 for sure 🚀 

Any question regarding this issue just tag me in the comments and will get back to you as soon as possible

👐 👐 👐

**Comment by luisFilipePT** [comment]
not stale
